#!/bin/sh
go get bazil.org/fuse
go get bazil.org/fuse/fs
go get github.com/bren2010/proquint
go get github.com/cenkalti/backoff
go get github.com/hashicorp/golang-lru
go get github.com/ipfs/go-bitswap
go get github.com/ipfs/go-bitswap/network
go get github.com/ipfs/go-block-format
go get github.com/ipfs/go-blockservice
go get github.com/ipfs/go-cid
go get github.com/ipfs/go-cidutil
go get github.com/ipfs/go-datastore
go get github.com/ipfs/go-datastore/namespace
go get github.com/ipfs/go-datastore/query
go get github.com/ipfs/go-datastore/retrystore
go get github.com/ipfs/go-datastore/sync
go get github.com/ipfs/go-ipfs-addr
go get github.com/ipfs/go-ipfs-blockstore
go get github.com/ipfs/go-ipfs-chunker
go get github.com/ipfs/go-ipfs-config
go get github.com/ipfs/go-ipfs-ds-help
go get github.com/ipfs/go-ipfs-exchange-interface
go get github.com/ipfs/go-ipfs-exchange-offline
go get github.com/ipfs/go-ipfs-files
go get github.com/ipfs/go-ipfs-posinfo
go get github.com/ipfs/go-ipfs-routing/none
go get github.com/ipfs/go-ipfs-routing/offline
go get github.com/ipfs/go-ipfs-util
go get github.com/ipfs/go-ipld-format
go get github.com/ipfs/go-ipns
go get github.com/ipfs/go-ipns/pb
go get github.com/ipfs/go-log
go get github.com/ipfs/go-merkledag
go get github.com/ipfs/go-merkledag/test
go get github.com/ipfs/go-metrics-interface
go get github.com/ipfs/go-mfs
go get github.com/ipfs/go-path
go get github.com/ipfs/go-path/resolver
go get github.com/ipfs/go-unixfs
go get github.com/ipfs/go-unixfs/file
go get github.com/ipfs/go-unixfs/importer/balanced
go get github.com/ipfs/go-unixfs/importer/helpers
go get github.com/ipfs/go-unixfs/importer/trickle
go get github.com/ipfs/go-unixfs/io
go get github.com/ipfs/go-verifcid
go get github.com/ipfs/interface-go-ipfs-core
go get github.com/ipfs/interface-go-ipfs-core/options
go get github.com/ipfs/interface-go-ipfs-core/options/namesys
go get github.com/jbenet/go-is-domain
go get github.com/jbenet/go-temp-err-catcher
go get github.com/jbenet/goprocess
go get github.com/jbenet/goprocess/context
go get github.com/jbenet/goprocess/periodic
go get github.com/libp2p/go-libp2p
go get github.com/libp2p/go-libp2p-autonat-svc
go get github.com/libp2p/go-libp2p-circuit
go get github.com/libp2p/go-libp2p-connmgr
go get github.com/libp2p/go-libp2p-host
go get github.com/libp2p/go-libp2p-interface-connmgr
go get github.com/libp2p/go-libp2p-kad-dht
go get github.com/libp2p/go-libp2p-kad-dht/opts
go get github.com/libp2p/go-libp2p-loggables
go get github.com/libp2p/go-libp2p-net
go get github.com/libp2p/go-libp2p-peerstore
go get github.com/libp2p/go-libp2p-peerstore/pstoremem
go get github.com/libp2p/go-libp2p-pnet
go get github.com/libp2p/go-libp2p-pubsub
go get github.com/libp2p/go-libp2p-pubsub-router
go get github.com/libp2p/go-libp2p-quic-transport
go get github.com/libp2p/go-libp2p-record
go get github.com/libp2p/go-libp2p-routing
go get github.com/libp2p/go-libp2p-routing-helpers
go get github.com/libp2p/go-libp2p-swarm
go get github.com/libp2p/go-libp2p/p2p/discovery
go get github.com/libp2p/go-libp2p/p2p/host/basic
go get github.com/libp2p/go-libp2p/p2p/host/routed
go get github.com/libp2p/go-libp2p/p2p/protocol/identify
go get github.com/libp2p/go-maddr-filter
go get github.com/libp2p/go-stream-muxer
go get github.com/whyrusleeping/base32
go get github.com/whyrusleeping/go-smux-multiplex
go get github.com/whyrusleeping/go-smux-yamux
go get github.com/whyrusleeping/multiaddr-filter
